#!/usr/bin/env bash

sudo -v

YELLOW=$'\033[1;33m'
NC=$'\033[0m'

function linkFile() {
    SRC="$1"
    DEST="$2"

    if [[ -f ${DEST} ]]; then
        rm -r "$DEST"
        ln -sf "$SRC" "$DEST"
    else
        ln -sf "$SRC" "$DEST"
    fi
}

function bootstrapTerminal() {
  echo ''
  echo -e "${YELLOW}------------------${NC}"
  echo -e "${YELLOW}Bootstrap Terminal${NC}"
  echo -e "${YELLOW}------------------${NC}"
  echo 'This will reset your terminal. Are you sure you want to to this? (y/n) '
  read -rp 'Answer: '  reply

  if [[ $reply =~ ^[Yy]$ ]]
  then
    if [[ ! -d $HOME/.oh-my-zsh ]]; then
      rm -rf "$HOME/.oh-my-zsh"
      curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
    fi
  fi
  echo ''
}

function freshInstall() {
  echo ''
  echo -e "${YELLOW}-------------${NC}"
  echo -e "${YELLOW}Fresh Install${NC}"
  echo -e "${YELLOW}-------------${NC}"
  echo 'Only use for a fresh installation of you Mac. Are you sure you want to to this? (y/n) '
  read -rp 'Answer: '  reply
  if [[ $reply =~ ^[Yy]$ ]]
  then
     source ./installer/bootstrap
  fi
  echo ''
}

function macSettings() {
  echo ''
  echo -e "${YELLOW}--------------------------${NC}"
  echo -e "${YELLOW}macOS settings from .macos${NC}"
  echo -e "${YELLOW}--------------------------${NC}"
  echo -e "Apply macOS settings from .macos? ${YELLOW}(reboot required!)${NC}: (y/n)"
  read -rp 'Answer: '  reply
  if [[ $reply =~ ^[Yy]$ ]]; then
    echo -e "\nApplying macOS default settings from ${YELLOW}.macos${NC} \n"
    source .macos
  fi
  echo ''
}

function init() {
  bootstrapTerminal
  linkFile "$HOME/.dotfiles/zsh/.zshrc" "$HOME/.zshrc"
  freshInstall
  macSettings

  touch "$HOME/.hushlogin" # Hide "last login" line when starting a new terminal session
  zsh # Run 'zsh' command to source new shell theme and settings.
}

init
