#!/usr/bin/env bash

sudo -v

YELLOW=$'\033[1;33m'
NC=$'\033[0m'

LOG_DIR="$HOME/.dotfiles/.log"

function log() {
  APP="$1"
  MESSAGE="$2"

  date "+[%d/%m/%Y %H:%M:%S] [$APP]: $MESSAGE" >> "$LOG_DIR/installer.log"
}

function createLogDir() {
  if [[ ! -d $LOG_DIR ]]; then
    mkdir -p "$LOG_DIR"
  fi
}

function symLinkFile() {
    SRC="$1"
    DEST="$2"

    if [[ -f "$DEST" ]]; then
        rm -r "$DEST"
        ln -sf "$SRC" "$DEST"
    else
        ln -sf "$SRC" "$DEST"
    fi
}

function newLine() {
  echo -e "\n"
}

function appIsInstalled() {
  log "$1" "Already installed."
  newLine
}

function zsh() {
  if [[ ! -d $HOME/.oh-my-zsh ]]; then
    log "$1" "Cleaning up before installing"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/uninstall.sh)"
    log "$1" "Installing $1"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  else
    appIsInstalled "$1"
  fi
}

function brew() {
  if test ! "$(which brew)"; then
    log "$1" "Cleaning up before installing"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
    log "$1" "Installing $1"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    newLine
  else
    appIsInstalled "Brew"
  fi

  brew tap homebrew/bundle
}

function install() {
  newLine
  echo -e "${YELLOW}-----------------${NC}"
  echo -e "${YELLOW}Install $1${NC}"
  echo -e "${YELLOW}-----------------${NC}"
  echo "This will uninstall, cleanup any remains of [$1] and install [$1]. Are you sure you want to to this? (y/n) "
  read -rp 'Answer: '  reply

  if [[ $reply =~ ^[Yy]$ ]]
  then
    if [[ $1 == "Oh My Zsh" ]]; then
      zsh "$1"
    else
      brew "$1"
    fi
  fi

  newLine
}

function init() {
  createLogDir
  echo -e "Setting up macOS Development Environment for: $USER"
  log "Installer" "Setting up macOS Development Environment for: $USER"

  install "Oh My Zsh"
  install "Brew"
  symLinkFile "$HOME/.dotfiles/zsh/.zshrc" "$HOME/.zshrc"

  newLine
  echo -e "${YELLOW}1. Make sure Google Drive is setup correctly, so sign into Google Drive if you haven't already.$NC"
  echo -e "${YELLOW}2. If you have a Mackup backup run "mackup restore" to restore settings of your applications. You'\''ll find more info on Mackup here: https://github.com/lra/mackup.$NC"

  touch "$HOME/.hushlogin" # Hide "last login" line when starting a new terminal session
  zsh # Run 'zsh' command to source new shell theme and settings.
}

init
