#!/usr/bin/env bash

sudo -v

function linkFile() {
    SRC="$1"
    DEST="$2"

    if [[ -f ${DEST} ]]; then
        rm -r "$DEST"
        ln -sf "$SRC" "$DEST"
    else
        ln -sf "$SRC" "$DEST"
    fi
}

function bootstrapTerminal() {
  if [[ ! -d $HOME/.oh-my-zsh ]]; then
    rm -rf "$HOME/.oh-my-zsh"
    curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
  fi

  linkFile "$HOME/.dotfiles/shell/.zshrc" "$HOME/.zshrc"
  linkFile "$HOME/.dotfiles/git/.global-gitignore" "$HOME/.global-gitignore"
}

function freshInstall() {
  echo ''
  echo '-------------'
  echo 'Fresh Install'
  echo '-------------'
  echo ''
  echo 'Only use for a fresh installation of you Mac. Are you sure you want to to this? (y/n) '
  read -rp 'Answer: '  reply
  if [[ $reply =~ ^[Yy]$ ]]
  then
     source ./installer/bootstrap
  fi
}

function macSettings() {
  echo ''
  echo '--------------------------'
  echo 'macOS settings from .macos'
  echo '--------------------------'
  echo ''
  read -p "Apply macOS settings from .macos? ${YELLOW}(reboot required!)${NC}: " -r
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo -e "\nApplying macOS default settings from ${YELLOW}.macos${NC} \n"
    source .macos
  fi
  echo ''
}

function init() {
  echo ''
  echo '------------------'
  echo 'Bootstrap Terminal'
  echo '------------------'
  echo ''
  echo 'This will reset your terminal. Are you sure you want to to this? (y/n) '
  read -rp 'Answer: '  reply

  if [[ $reply =~ ^[Yy]$ ]]
  then
     bootstrapTerminal
  fi

  freshInstall
  macSettings

  touch "$HOME/.hushlogin" # Hide "last login" line when starting a new terminal session
  zsh # Run 'zsh' command to source new shell theme and settings.
}

init
