version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "${FORWARD_DB_PORT:-33066}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE:-default}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - default
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s

  meilisearch:
    image: getmeili/meilisearch:v0.20.0
    ports:
      - "${FORWARD_MEILISEARCH_PORT:-7700}:7700"
    environment:
      HOST: https://meilisearch.test
    volumes:
      - meilisearch:/data.ms
    networks:
      - default
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health" ]
      retries: 3
      timeout: 5s

  redis:
    image: redis:6.2-alpine
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - redis:/data
    networks:
      - default
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "${FORWARD_MAILHOG_PORT:-1025}:1025"
      - "${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025"
    environment:
      HOST: https://mail.test
    networks:
      - default

  minio:
    image: minio/minio:latest
    ports:
      - "${FORWARD_MINIO_PORT:-9001}:9000"
    environment:
      MINIO_ROOT_USER: "job@app.com"
      MINIO_ROOT_PASSWORD: password
      HOST: https://cloud-storage.test
    volumes:
      - 'minio:/data/minio'
    networks:
      - default
    command: minio server /data/minio
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      retries: 3
      timeout: 5s

volumes:
  mysql:
    name: "mysql"
  meilisearch:
    name: "meilisearch"
  redis:
    name: "redis"
  minio:
    name: "minio"

networks:
  default:
