#!/usr/bin/env bash

sudo -v

source scripts/helpers.sh

newLine
echo -e "Setting up macOS Development Environment for: $USER"
logInstall "Init" "Setting up macOS Development Environment for: $USER"
newLine

# Install all our dependencies with bundle (See Brewfile)
brew tap homebrew/bundle
brew bundle

mkdir -p "$LOG_DIR"

source scripts/brew.sh
source scripts/php.sh

installBrew
setupPhp

newLine
echo -e "${YELLOW}1. Make sure iCloud is setup correctly, so sign into iCloud if you haven't already.$NC"
echo -e "${YELLOW}2. If you have a Mackup backup run `mackup restore` to restore settings of your applications. You'\''ll find more info on Mackup here: https://github.com/lra/mackup.$NC"

